### ISSUE TITLE
Which version is true?

### ISSUE THREAD

**Issue by new-soul** [supergreenlab/SuperGreenOS#5]
When I run "make -j4", it indicates the blew errors info. I think it was the different version.

`In file included from /Volumes/Data/Developer/ESP/SuperGreenOS/main/core/wifi/wifi.c:27:
/Users/Soul/esp/esp-idf/components/esp_event/include/esp_event_loop.h:2:2: warning: #warning "esp_event_loop.h is deprecated, please include esp_event.h instead" [-Wcpp]
 #warning "esp_event_loop.h is deprecated, please include esp_event.h instead"
  ^~~~~~~
/Volumes/Data/Developer/ESP/SuperGreenOS/main/core/wifi/wifi.c: In function 'init_wifi':
/Volumes/Data/Developer/ESP/SuperGreenOS/main/core/wifi/wifi.c:67:3: warning: 'esp_event_loop_init' is deprecated [-Wdeprecated-declarations]
   ESP_ERROR_CHECK( esp_event_loop_init(event_handler, NULL) );
   ^~~~~~~~~~~~~~~
In file included from /Users/Soul/esp/esp-idf/components/esp_event/include/esp_event.h:26,
                 from /Users/Soul/esp/esp-idf/components/esp_wifi/include/esp_wifi.h:64,
                 from /Volumes/Data/Developer/ESP/SuperGreenOS/main/core/wifi/wifi.c:26:
/Users/Soul/esp/esp-idf/components/esp_event/include/esp_event_legacy.h:231:11:note: declared here
 esp_err_t esp_event_loop_init(system_event_cb_t cb, void *ctx) __attribute__ ((deprecated));
           ^~~~~~~~~~~~~~~~~~~
CC build/libsodium/libsodium/src/libsodium/crypto_core/curve25519/ref10/curve25519_ref10.o
/Volumes/Data/Developer/ESP/SuperGreenOS/main/core/wifi/wifi.c:69:3: warning: 'tcpip_adapter_init' is deprecated [-Wdeprecated-declarations]
   tcpip_adapter_init();
   ^~~~~~~~~~~~~~~~~~
In file included from /Users/Soul/esp/esp-idf/components/esp_netif/include/esp_netif.h:35,
                 from /Users/Soul/esp/esp-idf/components/esp_event/include/esp_event_legacy.h:22,
                 from /Users/Soul/esp/esp-idf/components/esp_event/include/esp_event.h:26,
                 from /Users/Soul/esp/esp-idf/components/esp_wifi/include/esp_wifi.h:64,
                 from /Volumes/Data/Developer/ESP/SuperGreenOS/main/core/wifi/wifi.c:26:
/Users/Soul/esp/esp-idf/components/tcpip_adapter/include/tcpip_adapter.h:34:6: note: declared here
 void tcpip_adapter_init(void)  __attribute__ ((deprecated));
      ^~~~~~~~~~~~~~~~~~
/Volumes/Data/Developer/ESP/SuperGreenOS/main/core/wifi/wifi.c: In function 'event_handler':
/Volumes/Data/Developer/ESP/SuperGreenOS/main/core/wifi/wifi.c:214:3: warning: mdns_handle_system_event' is deprecated [-Wdeprecated-declarations]
   mdns_handle_system_event(ctx, event);
   ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Volumes/Data/Developer/ESP/SuperGreenOS/main/core/wifi/wifi.c:33:
/Users/Soul/esp/esp-idf/components/mdns/include/mdns.h:365:11: note: declared here
 esp_err_t mdns_handle_system_event(void *ctx, system_event_t *event) __attribute__((deprecated));
           ^~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by vitaminwater** [comment]
Make sure you are using the latest esp-idf version 3.x. The firmware is not yet ported to 4.x

**Comment by new-soul** [comment]
Thank you for your reply.
