### ISSUE TITLE
make -j4 flash monitor Fails "error: enumeration value 'MQTT_EVENT_DELETED'

### ISSUE THREAD

**Issue by Techn0Hippie** [supergreenlab/SuperGreenOS#6]
Hi SGL!
I am trying to flash your code onto a ESP32 module for testing. No issues installing dependencies (although they did not work in OSX, had to be done on a Ubuntu 18.04 box). When trying to flash to my esp32 I get the following error:

$ make -j4 flash monitor
Toolchain path: /home/pal/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: esp-2020r3
Compiler version: 8.4.0
Python requirements from /home/pal/esp/esp-idf/requirements.txt are satisfied.
Building partitions from /home/pal/SGL/SuperGreenOS/partitions.csv...
App "firmware" version: 820226b-dirty
CC build/main/core/mqtt/mqtt.o
CC build/main/core/kv/kv_helpers_internal.o
CC build/main/core/kv/kv_arrays.o
/home/pal/SGL/SuperGreenOS/main/core/mqtt/mqtt.c: In function 'mqtt_event_handler':
/home/pal/SGL/SuperGreenOS/main/core/mqtt/mqtt.c:45:3: error: enumeration value 'MQTT_EVENT_DELETED' not handled in switch [-Werror=switch]
   switch (event->event_id) {
   ^~~~~~
cc1: some warnings being treated as errors
/home/pal/esp/esp-idf/make/component_wrapper.mk:291: recipe for target 'core/mqtt/mqtt.o' failed
make[1]: *** [core/mqtt/mqtt.o] Error 1
make[1]: *** Waiting for unfinished jobs....
CC build/mdns/mdns_console.o
CC build/mdns/mdns_networking.o
CC build/mdns/mdns.o
/home/pal/esp/esp-idf/make/project.mk:635: recipe for target 'component-main-build' failed
make: *** [component-main-build] Error 2
make: *** Waiting for unfinished jobs....
AR build/mdns/libmdns.a

I have one of your Controllers, but I dont want to try to mess with it until I can be sure I can reflash it. Any idea what may be causing this? 
Importnat note: I am using firmware 820226b-dirty, is there another version I should use?

**Comment by vitaminwater** [comment]
Make sure you are using the latest esp-idf version 3.x. The firmware is not yet ported to 4.x.

**Comment by rastafd** [comment]
i have a similar isue
hi,

low the instruction even reinstall a fresh ubuntu 20 all go well just at the end
install esp-idf_release_3.3.1
make -j4

get the error
makefile:8: /make/project.mk: No such file or directory
make: *** No rule to make target '/make/project.mk'. Stop.



any pointer^

is there a place that we can get the bin file to push it whit NodeMCU-PyFlasher or something similar

Thanks

**Comment by vitaminwater** [comment]
I think that's a problem with env vars not being set.

I upl;oaded the firmware files [here](https://github.com/supergreenlab/SuperGreenOS/releases/tag/latest), you can directly flash it with the scripts in the zip with:

```sh
export SERIAL_PORT=/dev/ttyUSBx
./write_spiffs.sh && ./flash.sh
```

Make sure to replace `/dev/ttyUSBx` with the serial port on your computer.

**Comment by rastafd** [comment]
was not able to flash it whit those command but whit esp tool yes
i can access the web http://192.168.4.1/fs/app.html page but the android app "mobile data off" dose not download the controller info. 
![image](https://user-images.githubusercontent.com/76822625/137305644-215d4d11-d0a2-482f-9a04-b8ec42b6d208.png)

**Comment by vitaminwater** [comment]
Well you have a controller now, join the discord server at https://www.supergreenlab.com/discord I'll get you verified.
That will give you access to the support channel and the faq.
You can DM me, I'm @stant there.

**Comment by new-soul** [comment]
> I think that's a problem with env vars not being set.
> 
> I upl;oaded the firmware files [here](https://github.com/supergreenlab/SuperGreenOS/releases/tag/latest), you can directly flash it with the scripts in the zip with:
> 
> ```shell
> export SERIAL_PORT=/dev/ttyUSBx
> ./write_spiffs.sh && ./flash.sh
> ```
> 
> Make sure to replace `/dev/ttyUSBx` with the serial port on your computer.

Hi,vitaminwater,I builded the last 'bc9007e' which on Apr 18,then copy 'mkspiffs' to the dir.But when I access the web 'http://192.168.4.1/fs/app.html' show empty. What's the problem?
Is the html_app dir is different? 

> I think that's a problem with env vars not being set.
> 
> I upl;oaded the firmware files [here](https://github.com/supergreenlab/SuperGreenOS/releases/tag/latest), you can directly flash it with the scripts in the zip with:
> 
> ```shell
> export SERIAL_PORT=/dev/ttyUSBx
> ./write_spiffs.sh && ./flash.sh
> ```
> 
> Make sure to replace `/dev/ttyUSBx` with the serial port on your computer.

Hi,vitaminwater,I builded the last 'bc9007e' which on Apr 18, then copy 'mkspiffs' to the dir.But when I access the web 'http://192.168.4.1/fs/app.html' show empty. What's the problem?
Is the html_app dir is different?

**Comment by new-soul** [comment]
> I think that's a problem with env vars not being set.
> 
> I upl;oaded the firmware files [here](https://github.com/supergreenlab/SuperGreenOS/releases/tag/latest), you can directly flash it with the scripts in the zip with:
> 
> ```shell
> export SERIAL_PORT=/dev/ttyUSBx
> ./write_spiffs.sh && ./flash.sh
> ```
> 
> Make sure to replace `/dev/ttyUSBx` with the serial port on your computer.

Hi,vitaminwater,I builded the last 'bc9007e' which on Apr 18,then copy 'mkspiffs' to the dir.But when I access the web 'http://192.168.4.1/fs/app.html' show empty. What's the problem?
Is the html_app dir is different? 

> I think that's a problem with env vars not being set.
> 
> I upl;oaded the firmware files [here](https://github.com/supergreenlab/SuperGreenOS/releases/tag/latest), you can directly flash it with the scripts in the zip with:
> 
> ```shell
> export SERIAL_PORT=/dev/ttyUSBx
> ./write_spiffs.sh && ./flash.sh
> ```
> 
> Make sure to replace `/dev/ttyUSBx` with the serial port on your computer.

Hi,vitaminwater,I builded the last 'bc9007e' which on Apr 18,then copy 'mkspiffs' to the dir.But when I access the web 'http://192.168.4.1/fs/app.html' show empty. What's the problem?
Is the html_app dir is different?

**Comment by new-soul** [comment]
> > I think that's a problem with env vars not being set.
> > I upl;oaded the firmware files [here](https://github.com/supergreenlab/SuperGreenOS/releases/tag/latest), you can directly flash it with the scripts in the zip with:
> > ```shell
> > export SERIAL_PORT=/dev/ttyUSBx
> > ./write_spiffs.sh && ./flash.sh
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Make sure to replace `/dev/ttyUSBx` with the serial port on your computer.
> 
> Hi,vitaminwater,I builded the last 'bc9007e' which on Apr 18,then copy 'mkspiffs' to the dir.But when I access the web 'http://192.168.4.1/fs/app.html' show empty. What's the problem? Is the html_app dir is different?
> 
> > I think that's a problem with env vars not being set.
> > I upl;oaded the firmware files [here](https://github.com/supergreenlab/SuperGreenOS/releases/tag/latest), you can directly flash it with the scripts in the zip with:
> > ```shell
> > export SERIAL_PORT=/dev/ttyUSBx
> > ./write_spiffs.sh && ./flash.sh
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Make sure to replace `/dev/ttyUSBx` with the serial port on your computer.
> 
> Hi,vitaminwater,I builded the last 'bc9007e' which on Apr 18,then copy 'mkspiffs' to the dir.But when I access the web 'http://192.168.4.1/fs/app.html' show empty. What's the problem? Is the html_app dir is different?

I copied the 1628596512's spiffs.bin to write is ok.And the size of both is the same.
In addition, I copied 1628596512's html_app to master and run write_spiffs.sh is also show empty page.
What's the problem?

**Comment by vitaminwater** [comment]
Check this [guide](https://picofarmled.com/guide/how-to-setup-pico-farm-os) (work in pogress) for how to flash the whole thing, and an up-to-date version
